application: hello-flask-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
  secure: always    #always use http

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: ssl # app needs latest version of ssl module
  version: latest

